settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: goliff
  path: .
  commands:
    install:
      status: true
      method: go build -o goliff
    run:
      status: true
      method: ./goliff
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
