version: "3.8"

services:
  web:
    container_name: goliff
    image: golang:alpine3.12
    restart: always
    ports:
      - 8080:8080
    environment:
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      DATABASE_URL: jdbc:postgresql://db:5432/goliff
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - $PWD:/github.com/captainblue210/goliff
    working_dir: /github.com/captainblue210/goliff
    depends_on:
      - db
    command: ["go", "run", "server.go"]

  db:
    container_name: goliff-db
    image: postgres:12-alpine
    restart: always
    ports:
      - 5433:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    volumes:
      - $PWD/docker/db/init:/docker-entrypoint-initdb.d
      - "dbdata:/var/lib/postgresql/data"

volumes:
  dbdata:
